### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds 

### ISSUE THREAD

**Issue by SafwanElmadani** [jmscslgroup/strym#26]
strym version: 0.3.6
I'm getting this error when using strymread.ts_sync() to resample two time series data. 

![image](https://user-images.githubusercontent.com/35984199/99848477-162a5200-2b37-11eb-93d7-a26bf64df76a.png)

**Comment by rahulbhadani** [comment]
There were a couple of bugs and issues encountered while tracking down this problem:

- The portion of code that removes duplicated indices had a bug
- When concatenating multiple data frames from all 16 traces of radar, then the final data frame must be sorted by Time
- When specifying two data frames to `ts_sync` there must at least be an overlap of two timeseries data frames in time,
